# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'PublishTemplates'
  displayName: 'Publish Templates'
  jobs: 
  - job: 'PublishTemplates'
    steps:
      - script: echo $(Build.StagingDirectory)
        displayName: 'Run a one-line script'

- stage: 'DelployTemplates'
  displayName: 'Deploy Templates'
  jobs: 
  - job: 'DelployTemplates'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         #echo $(Build.SourcesDirectory)
         displayName: 'Run a multi-line script'

- stage: 'Update'
  displayName: 'Update'
  jobs: 
  - job: 'Update'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         #echo $(Build.SourcesDirectory)
         displayName: 'Run a multi-line script'