# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: 'GetTestCase'
  displayName: 'GetTestCase'
  jobs: 
  - job: 'PublishTemplates'
    steps:
      - script: echo $(Build.StagingDirectory)
        displayName: 'Run a one-line script'

- stage: 'BuildUPToolchain'
  displayName: 'BuildUp Toolchain '
  jobs: 
  - job: 'DelployTemplates'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         echo E N V I R O N M E N T 
         echo $env 
        displayName: 'Deploy'

- stage: 'VerifyTCInstallation'
  displayName:  'Verify Toolchain installation'
  jobs: 
  - job: 'Verify'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         #echo $(Build.SourcesDirectory)
        displayName: 'a multi-line script'

- stage: 'ExecToolchainTests'
  displayName:  'ExecTestsForToolchain'
  jobs: 
  - job: 'VerifyInstallation'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         #echo $(Build.SourcesDirectory)
        displayName: 'a multi-line script'

- stage: ''
  displayName:  'UploadTestresult'
  jobs: 
  - job: 'UploadResultsToTMS'
    steps:
      - script: |
         echo Add other tasks to build, test, and deploy your project.
         #echo $(Build.SourcesDirectory)
        displayName: 'a multi-line script'
